<?php

namespace Database\Seeders;

use App\Models\Gym;
use Illuminate\Database\Seeder;

class GymSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gyms = [
            [
                'name' => 'FitZone Gym',
                'address' => '12 Rue Mohammed V, Casablanca',
                'latitude' => 33.5731104,
                'longitude' => -7.5898434,
                'rating' => 4.8,
                'opening_hours' => '06:00 - 22:00',
                'facilities' => ['Cardio', 'Weights', 'Classes'],
                'is_active' => true,
            ],
            [
                'name' => 'PowerHouse Fitness',
                'address' => '34 Boulevard Anfa, Casablanca',
                'latitude' => 33.5851104,
                'longitude' => -7.6018434,
                'rating' => 4.5,
                'opening_hours' => '07:00 - 23:00',
                'facilities' => ['CrossFit', 'Sauna', 'Pool'],
                'is_active' => true,
            ],
            [
                'name' => 'Elite Sports Club',
                'address' => '7 Rue Ibnou Sina, Casablanca',
                'latitude' => 33.5921104,
                'longitude' => -7.6128434,
                'rating' => 4.3,
                'opening_hours' => '06:30 - 21:00',
                'facilities' => ['Yoga', 'Boxing', 'Weights'],
                'is_active' => true,
            ],
            [
                'name' => 'Urban Athlete',
                'address' => '88 Avenue Hassan II, Casablanca',
                'latitude' => 33.5981104,
                'longitude' => -7.6208434,
                'rating' => 4.6,
                'opening_hours' => '06:00 - 22:30',
                'facilities' => ['HIIT', 'Cycling', 'Nutrition'],
                'is_active' => true,
            ],
            [
                'name' => 'Iron Paradise Gym',
                'address' => '15 Rue Goulmima, Casablanca',
                'latitude' => 33.5681104,
                'longitude' => -7.6308434,
                'rating' => 4.7,
                'opening_hours' => '05:00 - 23:00',
                'facilities' => ['Heavy Weights', 'Powerlifting', 'Personal Training'],
                'is_active' => true,
            ],
            [
                'name' => 'Olympus Strength Gym',
                'address' => '50 Boulevard Zerktouni, Casablanca',
                'latitude' => 33.5781104,
                'longitude' => -7.6408434,
                'rating' => 4.9,
                'opening_hours' => '06:00 - 23:00',
                'facilities' => ['Bodybuilding', 'Cardio', 'Sauna', 'Juice Bar'],
                'is_active' => true,
            ],
            [
                'name' => 'Casablanca CrossFit',
                'address' => '22 Boulevard Rachidi, Casablanca',
                'latitude' => 33.5881104,
                'longitude' => -7.6188434,
                'rating' => 4.8,
                'opening_hours' => '06:00 - 21:00',
                'facilities' => ['CrossFit', 'Gymnastics', 'Olympic Lifting'],
                'is_active' => true,
            ],
            [
                'name' => 'Pulse Fitness Club',
                'address' => '104 Boulevard de Paris, Casablanca',
                'latitude' => 33.5931104,
                'longitude' => -7.6148434,
                'rating' => 4.4,
                'opening_hours' => '07:00 - 22:00',
                'facilities' => ['Zumba', 'Spinning', 'Pilates'],
                'is_active' => true,
            ],
            [
                'name' => 'Titanium Gym',
                'address' => '45 Rue de Rome, Casablanca',
                'latitude' => 33.5821104,
                'longitude' => -7.6088434,
                'rating' => 4.6,
                'opening_hours' => '05:30 - 22:30',
                'facilities' => ['Cardio', 'Strength Machines', 'Boxing Ring'],
                'is_active' => true,
            ],
            [
                'name' => 'Apex Health Club',
                'address' => '77 Avenue Pasteur, Casablanca',
                'latitude' => 33.5701104,
                'longitude' => -7.6258434,
                'rating' => 4.5,
                'opening_hours' => '06:00 - 22:00',
                'facilities' => ['Steam Room', 'Swimming Pool', 'Yoga Studio'],
                'is_active' => true,
            ],
            [
                'name' => 'Gold Standard Fitness',
                'address' => '19 Boulevard de la Corniche, Casablanca',
                'latitude' => 33.5991104,
                'longitude' => -7.6608434,
                'rating' => 4.7,
                'opening_hours' => '24 Hours',
                'facilities' => ['24/7 Access', 'Luxury Showers', 'Cryotherapy'],
                'is_active' => true,
            ],
            [
                'name' => 'The Muscle Factory',
                'address' => '65 Boulevard Abdelmoumen, Casablanca',
                'latitude' => 33.5751104,
                'longitude' => -7.6158434,
                'rating' => 4.3,
                'opening_hours' => '06:00 - 22:00',
                'facilities' => ['Weights', 'Dumbbells', 'Cardio Deck'],
                'is_active' => true,
            ],
            [
                'name' => 'Elevate Fitness Studio',
                'address' => '120 Route d\'El Jadida, Casablanca',
                'latitude' => 33.5501104,
                'longitude' => -7.6408434,
                'rating' => 4.6,
                'opening_hours' => '07:00 - 21:00',
                'facilities' => ['TRX Training', 'Kettlebells', 'Group Classes'],
                'is_active' => true,
            ],
            [
                'name' => 'Athena Women Gym',
                'address' => '8 Avenue 2 Mars, Casablanca',
                'latitude' => 33.5651104,
                'longitude' => -7.6108434,
                'rating' => 4.8,
                'opening_hours' => '08:00 - 21:00',
                'facilities' => ['Ladies Only', 'Pilates', 'Zumba', 'Massage Therapy'],
                'is_active' => true,
            ],
            [
                'name' => 'Vibe Health Club',
                'address' => '90 Rue Tarik Ibn Ziad, Casablanca',
                'latitude' => 33.5801104,
                'longitude' => -7.6228434,
                'rating' => 4.4,
                'opening_hours' => '06:00 - 22:00',
                'facilities' => ['Cycling Studio', 'Cardio', 'Sauna'],
                'is_active' => true,
            ],
            [
                'name' => 'Dynamic Strength Lab',
                'address' => '14 Boulevard de Libye, Casablanca',
                'latitude' => 33.5711104,
                'longitude' => -7.5958434,
                'rating' => 4.5,
                'opening_hours' => '06:00 - 21:30',
                'facilities' => ['Functional Training', 'Calisthenics', 'Gymnastic Rings'],
                'is_active' => true,
            ],
            [
                'name' => 'Legacy Gym',
                'address' => '25 Avenue de la Marne, Casablanca',
                'latitude' => 33.5841104,
                'longitude' => -7.6328434,
                'rating' => 4.2,
                'opening_hours' => '07:00 - 22:00',
                'facilities' => ['Weights', 'Personal Training', 'Cardio Machines'],
                'is_active' => true,
            ],
            [
                'name' => 'Velocity Gym & Spa',
                'address' => '55 Avenue Nador, Casablanca',
                'latitude' => 33.5551104,
                'longitude' => -7.6058434,
                'rating' => 4.7,
                'opening_hours' => '06:00 - 23:00',
                'facilities' => ['Spa', 'Heated Pool', 'CrossFit Box', 'Yoga'],
                'is_active' => true,
            ],
            [
                'name' => 'Zenith Fitness',
                'address' => '201 Boulevard Sidi Abderrahmane, Casablanca',
                'latitude' => 33.5891104,
                'longitude' => -7.6758434,
                'rating' => 4.6,
                'opening_hours' => '07:00 - 22:00',
                'facilities' => ['Stretching Area', 'Pilates Reformers', 'Juice Bar'],
                'is_active' => true,
            ],
            [
                'name' => 'Impact Fight & Fitness',
                'address' => '10 Rue de Fes, Casablanca',
                'latitude' => 33.5901104,
                'longitude' => -7.6008434,
                'rating' => 4.9,
                'opening_hours' => '08:00 - 22:30',
                'facilities' => ['Kickboxing', 'MMA', 'Muay Thai', 'Strength Area'],
                'is_active' => true,
            ],
        ];

        foreach ($gyms as $gym) {
            Gym::updateOrCreate(
                ['name' => $gym['name']],
                $gym
            );
        }
    }
}
