<?php

namespace Database\Seeders;

use App\Models\Pharmacy;
use Illuminate\Database\Seeder;

class PharmacySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pharmacies = [
            [
                'name' => 'Care & Cure Pharmacy',
                'address' => '12 Rue Mohammed V, Casablanca',
                'phone' => '+212-522-112233',
                'latitude' => 33.5731104,
                'longitude' => -7.5898434,
                'rating' => 4.8,
                'opening_hours' => '08:00 - 22:00',
                'services' => ['Prescription Delivery', 'Vaccinations', 'Blood Pressure Check'],
                'is_active' => true,
            ],
            [
                'name' => 'MediSave Pharmacy',
                'address' => '34 Boulevard Anfa, Casablanca',
                'phone' => '+212-522-445566',
                'latitude' => 33.5851104,
                'longitude' => -7.6018434,
                'rating' => 4.5,
                'opening_hours' => '24 Hours',
                'services' => ['Emergency Rx', 'Drive-Thru', 'Diabetes Consultation'],
                'is_active' => true,
            ],
            [
                'name' => 'LifeLine Pharma',
                'address' => '7 Rue Ibnou Sina, Casablanca',
                'phone' => '+212-522-778899',
                'latitude' => 33.5921104,
                'longitude' => -7.6128434,
                'rating' => 4.3,
                'opening_hours' => '08:00 - 21:00',
                'services' => ['Online Refills', 'Flu Shots', 'Medical Supplies'],
                'is_active' => true,
            ],
            [
                'name' => 'Wellness Pharmacy',
                'address' => '88 Avenue Hassan II, Casablanca',
                'phone' => '+212-522-102030',
                'latitude' => 33.5981104,
                'longitude' => -7.6208434,
                'rating' => 4.6,
                'opening_hours' => '08:30 - 22:00',
                'services' => ['Compounding', 'Immunizations', 'Home Delivery'],
                'is_active' => true,
            ],
            [
                'name' => 'QuickRx Pharmacy',
                'address' => '15 Rue Goulmima, Casablanca',
                'phone' => '+212-522-405060',
                'latitude' => 33.5681104,
                'longitude' => -7.6308434,
                'rating' => 4.7,
                'opening_hours' => '08:00 - 23:00',
                'services' => ['Curbside Pickup', 'Medication Synchronization', 'Pet Meds'],
                'is_active' => true,
            ],
            [
                'name' => 'The Family Chemist',
                'address' => '50 Boulevard Zerktouni, Casablanca',
                'phone' => '+212-522-708090',
                'latitude' => 33.5781104,
                'longitude' => -7.6408434,
                'rating' => 4.4,
                'opening_hours' => '09:00 - 21:00',
                'services' => ['Health Consultations', 'Travel Vaccinations', 'Vitamin Center'],
                'is_active' => true,
            ],
            [
                'name' => 'CureAll Pharmacy',
                'address' => '22 Boulevard Rachidi, Casablanca',
                'phone' => '+212-522-123456',
                'latitude' => 33.5881104,
                'longitude' => -7.6188434,
                'rating' => 4.9,
                'opening_hours' => '24 Hours',
                'services' => ['24/7 Service', 'Oxygen Concentrators', 'Home Delivery'],
                'is_active' => true,
            ],
            [
                'name' => 'City Center Pharmacy',
                'address' => '104 Boulevard de Paris, Casablanca',
                'phone' => '+212-522-654321',
                'latitude' => 33.5931104,
                'longitude' => -7.6148434,
                'rating' => 4.2,
                'opening_hours' => '08:00 - 20:00',
                'services' => ['Blood Glucose Testing', 'Weight Management', 'Baby Care'],
                'is_active' => true,
            ],
            [
                'name' => 'Apex Pharmacy',
                'address' => '45 Rue de Rome, Casablanca',
                'phone' => '+212-522-987654',
                'latitude' => 33.5821104,
                'longitude' => -7.6088434,
                'rating' => 4.7,
                'opening_hours' => '08:00 - 22:00',
                'services' => ['Cardiology Care', 'Specialty Drugs', 'Senior Discounts'],
                'is_active' => true,
            ],
            [
                'name' => 'Pulse Pharmacy',
                'address' => '77 Avenue Pasteur, Casablanca',
                'phone' => '+212-522-135790',
                'latitude' => 33.5701104,
                'longitude' => -7.6258434,
                'rating' => 4.8,
                'opening_hours' => '07:30 - 22:30',
                'services' => ['Strep Testing', 'Cholesterol Screening', 'Medication Management'],
                'is_active' => true,
            ],
            [
                'name' => 'Healthy Life Pharmacy',
                'address' => '19 Boulevard de la Corniche, Casablanca',
                'phone' => '+212-522-246801',
                'latitude' => 33.5991104,
                'longitude' => -7.6608434,
                'rating' => 4.6,
                'opening_hours' => '09:00 - 23:00',
                'services' => ['Herbal Supplements', 'Skincare Consultations', 'Home Delivery'],
                'is_active' => true,
            ],
            [
                'name' => 'Metro Pharmacy',
                'address' => '65 Boulevard Abdelmoumen, Casablanca',
                'phone' => '+212-522-112244',
                'latitude' => 33.5751104,
                'longitude' => -7.6158434,
                'rating' => 4.5,
                'opening_hours' => '08:00 - 22:00',
                'services' => ['Prescription Refills', 'Hormone Therapy', 'First Aid Supplies'],
                'is_active' => true,
            ],
            [
                'name' => 'Standard Pharmacy',
                'address' => '120 Route d\'El Jadida, Casablanca',
                'phone' => '+212-522-556677',
                'latitude' => 33.5501104,
                'longitude' => -7.6408434,
                'rating' => 4.3,
                'opening_hours' => '08:30 - 21:30',
                'services' => ['Generic Substitutions', 'Asthma Management', 'Wheelchair Rental'],
                'is_active' => true,
            ],
            [
                'name' => 'Green Cross Pharmacy',
                'address' => '8 Avenue 2 Mars, Casablanca',
                'phone' => '+212-522-889900',
                'latitude' => 33.5651104,
                'longitude' => -7.6108434,
                'rating' => 4.7,
                'opening_hours' => '08:00 - 22:00',
                'services' => ['Natural Products', 'Diabetes Care', 'Medication Disposal'],
                'is_active' => true,
            ],
            [
                'name' => 'PharmaCare',
                'address' => '90 Rue Tarik Ibn Ziad, Casablanca',
                'phone' => '+212-522-223344',
                'latitude' => 33.5801104,
                'longitude' => -7.6228434,
                'rating' => 4.4,
                'opening_hours' => '08:00 - 21:00',
                'services' => ['Consultation Rooms', 'Wound Care', 'Multi-dose Packaging'],
                'is_active' => true,
            ],
            [
                'name' => 'Evergreen Pharmacy',
                'address' => '14 Boulevard de Libye, Casablanca',
                'phone' => '+212-522-667788',
                'latitude' => 33.5711104,
                'longitude' => -7.5958434,
                'rating' => 4.9,
                'opening_hours' => '24 Hours',
                'services' => ['24/7 Delivery', 'Custom Compounding', 'Flu Vaccines'],
                'is_active' => true,
            ],
            [
                'name' => 'Corner Drug Store',
                'address' => '25 Avenue de la Marne, Casablanca',
                'phone' => '+212-522-990011',
                'latitude' => 33.5841104,
                'longitude' => -7.6328434,
                'rating' => 4.1,
                'opening_hours' => '09:00 - 20:00',
                'services' => ['Local Delivery', 'Photo Printing', 'Personal Care Needs'],
                'is_active' => true,
            ],
            [
                'name' => 'Reliable Pharmacy',
                'address' => '55 Avenue Nador, Casablanca',
                'phone' => '+212-522-334455',
                'latitude' => 33.5551104,
                'longitude' => -7.6058434,
                'rating' => 4.6,
                'opening_hours' => '08:00 - 22:00',
                'services' => ['Vitamins & Supplements', 'Health Education', 'Free Delivery'],
                'is_active' => true,
            ],
            [
                'name' => 'Nova Pharmacy',
                'address' => '201 Boulevard Sidi Abderrahmane, Casablanca',
                'phone' => '+212-522-778800',
                'latitude' => 33.5891104,
                'longitude' => -7.6758434,
                'rating' => 4.8,
                'opening_hours' => '08:00 - 23:00',
                'services' => ['Drive-Thru Pharmacy', 'Pneumonia Shots', 'Prescription Transfer'],
                'is_active' => true,
            ],
            [
                'name' => 'Guardian Pharmacy',
                'address' => '10 Rue de Fes, Casablanca',
                'phone' => '+212-522-441100',
                'latitude' => 33.5901104,
                'longitude' => -7.6008434,
                'rating' => 4.7,
                'opening_hours' => '07:30 - 22:00',
                'services' => ['Immunization Service', 'Weekly Pill Organizers', 'Home Delivery'],
                'is_active' => true,
            ],
        ];

        foreach ($pharmacies as $pharmacy) {
            Pharmacy::updateOrCreate(
                ['name' => $pharmacy['name']],
                $pharmacy
            );
        }
    }
}
