<?php

namespace Database\Seeders;

use App\Models\Specialist;
use Illuminate\Database\Seeder;

class SpecialistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specialists = [
            [
                'name' => 'Dr. Sarah Jenkins',
                'title' => 'Clinical Nutritionist',
                'email' => 'sarah.jenkins@example.com',
                'phone' => '+1-555-0191',
                'avatar' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150',
                'specialties' => ['Weight Management', 'Clinical Nutrition', 'Diabetes Diet'],
                'bio' => 'Dr. Sarah has over 10 years of experience in clinical nutrition, helping patients manage chronic illnesses through custom diet programs.',
                'available_slots' => ['09:00 AM', '10:30 AM', '02:00 PM', '04:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. John Miller',
                'title' => 'Sports Dietitian',
                'email' => 'john.miller@example.com',
                'phone' => '+1-555-0192',
                'avatar' => 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150',
                'specialties' => ['Sports Nutrition', 'Muscle Gain', 'Endurance Prep'],
                'bio' => 'A certified sports nutrition expert, Dr. John works with professional athletes to optimize energy levels and performance.',
                'available_slots' => ['08:00 AM', '11:00 AM', '01:00 PM', '03:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Emily Smith',
                'title' => 'Pediatric Dietitian',
                'email' => 'emily.smith@example.com',
                'phone' => '+1-555-0193',
                'avatar' => 'https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150',
                'specialties' => ['Pediatric Nutrition', 'Childhood Obesity', 'Picky Eaters'],
                'bio' => 'Specializing in child growth and nutrition, Dr. Emily helps parents cultivate healthy eating habits in children.',
                'available_slots' => ['10:00 AM', '11:30 AM', '03:00 PM', '05:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Marcus Vance',
                'title' => 'Cardiovascular Nutritionist',
                'email' => 'marcus.vance@example.com',
                'phone' => '+1-555-0194',
                'avatar' => 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150',
                'specialties' => ['Heart Health', 'Cholesterol Control', 'Hypertension Diet'],
                'bio' => 'Dr. Marcus helps patients design heart-healthy nutrition plans to lower cholesterol and blood pressure naturally.',
                'available_slots' => ['09:30 AM', '12:00 PM', '02:30 PM', '04:30 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Lisa Wong',
                'title' => 'Gastroenterology Nutritionist',
                'email' => 'lisa.wong@example.com',
                'phone' => '+1-555-0195',
                'avatar' => 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=150',
                'specialties' => ['IBS Diet', 'Gut Health', 'Celiac Disease'],
                'bio' => 'Lisa is dedicated to solving complex digestive problems, creating personalized FODMAP plans for optimal gut comfort.',
                'available_slots' => ['08:30 AM', '10:00 AM', '01:30 PM', '03:30 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Robert Davis',
                'title' => 'Endocrinology Specialist',
                'email' => 'robert.davis@example.com',
                'phone' => '+1-555-0196',
                'avatar' => 'https://images.unsplash.com/photo-1582750433449-64c656fb19f0?w=150',
                'specialties' => ['Thyroid Health', 'PCOS Management', 'Hormonal Balance'],
                'bio' => 'Focused on endocrine wellness, Dr. Robert supports patients experiencing hormonal issues like PCOS and thyroid imbalances.',
                'available_slots' => ['11:00 AM', '02:00 PM', '03:00 PM', '05:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Angela Rossi',
                'title' => 'Weight Loss Coach',
                'email' => 'angela.rossi@example.com',
                'phone' => '+1-555-0197',
                'avatar' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
                'specialties' => ['Weight Management', 'Mindful Eating', 'Ketogenic Diet'],
                'bio' => 'Angela focuses on behavior modification and tailored metabolic plans to make weight management sustainable.',
                'available_slots' => ['09:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. David Kim',
                'title' => 'Geriatric Nutritionist',
                'email' => 'david.kim@example.com',
                'phone' => '+1-555-0198',
                'avatar' => 'https://images.unsplash.com/photo-1607990283143-e81e7a2c93ab?w=150',
                'specialties' => ['Elderly Nutrition', 'Bone Density Diet', 'Muscle Retention'],
                'bio' => 'Supporting wellness in aging, Dr. David designs diets rich in key nutrients to keep seniors strong and energetic.',
                'available_slots' => ['10:00 AM', '12:00 PM', '01:00 PM', '03:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Sophia Martinez',
                'title' => 'Oncology Nutritionist',
                'email' => 'sophia.martinez@example.com',
                'phone' => '+1-555-0199',
                'avatar' => 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?w=150',
                'specialties' => ['Cancer Support', 'Immunonutrition', 'Recovery Diet'],
                'bio' => 'Dr. Sophia specializes in optimizing nutritional health and resilience for patients undergoing oncology treatment.',
                'available_slots' => ['09:00 AM', '11:00 AM', '02:30 PM', '04:30 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. James Wilson',
                'title' => 'Renal Dietitian',
                'email' => 'james.wilson@example.com',
                'phone' => '+1-555-0200',
                'avatar' => 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150',
                'specialties' => ['Kidney Health', 'Low Sodium Diet', 'CKD Management'],
                'bio' => 'James offers meticulous nutritional counseling for chronic kidney disease (CKD) and post-transplant kidney health.',
                'available_slots' => ['08:00 AM', '10:00 AM', '01:00 PM', '03:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Natalie Petit',
                'title' => 'Holistic Nutritionist',
                'email' => 'natalie.petit@example.com',
                'phone' => '+1-555-0201',
                'avatar' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150',
                'specialties' => ['Plant-Based Diet', 'Detox Programs', 'Herbal Support'],
                'bio' => 'Natalie integrates whole foods, herbs, and healthy lifestyles to promote total mind-body health and vitality.',
                'available_slots' => ['09:00 AM', '11:30 AM', '02:00 PM', '04:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Thomas Wright',
                'title' => 'Metabolic Specialist',
                'email' => 'thomas.wright@example.com',
                'phone' => '+1-555-0202',
                'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
                'specialties' => ['Metabolic Syndrome', 'Insulin Resistance', 'Keto Diet'],
                'bio' => 'Dr. Thomas targets underlying metabolic dysfunctions with custom dietary regimens and insulin sensitivity therapy.',
                'available_slots' => ['10:00 AM', '01:00 PM', '03:00 PM', '05:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Elena Rostova',
                'title' => 'Allergy Dietitian',
                'email' => 'elena.rostova@example.com',
                'phone' => '+1-555-0203',
                'avatar' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
                'specialties' => ['Food Allergies', 'Elimination Diets', 'Histamine Intolerance'],
                'bio' => 'Elena helps families navigate complex dietary restrictions, dairy-free, and gluten-free lifestyles safely.',
                'available_slots' => ['08:30 AM', '11:00 AM', '01:30 PM', '04:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Kevin Patel',
                'title' => 'Bariatric Dietitian',
                'email' => 'kevin.patel@example.com',
                'phone' => '+1-555-0204',
                'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
                'specialties' => ['Post-Surgery Diet', 'Portion Control', 'Bariatric Success'],
                'bio' => 'Dr. Kevin guides patients before and after bariatric surgery, ensuring complete nutrient absorption and long-term success.',
                'available_slots' => ['09:00 AM', '12:00 PM', '02:00 PM', '04:30 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Rachel Green',
                'title' => 'Prenatal Dietitian',
                'email' => 'rachel.green@example.com',
                'phone' => '+1-555-0205',
                'avatar' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
                'specialties' => ['Pregnancy Diet', 'Gestational Diabetes', 'Lactation'],
                'bio' => 'Rachel supports expecting mothers with diets that optimize baby development and control gestational diabetes risk.',
                'available_slots' => ['10:00 AM', '11:30 AM', '01:00 PM', '03:30 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Alan Harper',
                'title' => 'Behavioral Dietitian',
                'email' => 'alan.harper@example.com',
                'phone' => '+1-555-0206',
                'avatar' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
                'specialties' => ['Eating Disorders', 'Intuitive Eating', 'Food Relationship'],
                'bio' => 'Dr. Alan helps clients rebuild a healthy relationship with food, focusing on overcoming emotional and disordered eating.',
                'available_slots' => ['09:00 AM', '10:30 AM', '02:00 PM', '04:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Chloe Frazer',
                'title' => 'Sports & Youth Dietitian',
                'email' => 'chloe.frazer@example.com',
                'phone' => '+1-555-0207',
                'avatar' => 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150',
                'specialties' => ['Teen Athletes', 'Meal Prep', 'High Energy Diets'],
                'bio' => 'Chloe works with youth athletic organizations, developing programs for growing teen sports stars.',
                'available_slots' => ['11:00 AM', '01:00 PM', '03:00 PM', '05:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Victor Stone',
                'title' => 'Fitness & Rehab Dietitian',
                'email' => 'victor.stone@example.com',
                'phone' => '+1-555-0208',
                'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
                'specialties' => ['Injury Recovery', 'Joint Health', 'Anti-Inflammatory'],
                'bio' => 'Dr. Victor focuses on foods that speed up physical recovery from muscle injuries and joint wear.',
                'available_slots' => ['08:00 AM', '10:00 AM', '02:00 PM', '04:00 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Laura Croft',
                'title' => 'Adventure Dietitian',
                'email' => 'laura.croft@example.com',
                'phone' => '+1-555-0209',
                'avatar' => 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150',
                'specialties' => ['Extreme Endurance', 'High Altitude Nutrition', 'Keto'],
                'bio' => 'Laura guides mountaineers and wilderness explorers in nutrition requirements for extreme survival and expeditions.',
                'available_slots' => ['09:00 AM', '12:00 PM', '03:00 PM', '04:30 PM'],
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Bruce Wayne',
                'title' => 'Sleep & Stress Nutritionist',
                'email' => 'bruce.wayne@example.com',
                'phone' => '+1-555-0210',
                'avatar' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
                'specialties' => ['Stress Control', 'Sleep Improvement', 'Brain Health'],
                'bio' => 'Bruce designs nutrition profiles that lower cortisol levels, optimize cognitive focus, and improve sleep cycles.',
                'available_slots' => ['10:00 AM', '02:00 PM', '03:30 PM', '05:00 PM'],
                'is_active' => true,
            ],
        ];

        foreach ($specialists as $specialist) {
            Specialist::updateOrCreate(
                ['email' => $specialist['email']],
                $specialist
            );
        }
    }
}
